#!/usr/bin/python

import sys

def extractOutput(file):
	outputs = [] #All possible outputs
	output = [] #A single possible output
	with open(file, 'r') as f:
		for line in f.readlines():
			line = line.strip()
			if line.lower() == 'or': #Finish the 1 of the possible results
				outputs.append(output) 
				output = []
				continue
			output.append(line)
	outputs.append(output)
	return outputs


def main():
	if len(sys.argv) != 3:
		print "USAGE: testOutput.py expected_file output_file"
		exit(1)
	exp_file = sys.argv[1]
	out_file = sys.argv[2]
	actual_output = extractOutput(out_file)[0] #Get Actual output
	expected_outputs = extractOutput(exp_file)
	for expected_output in expected_outputs:
		if actual_output == expected_output:
			print "PASSED: " + exp_file #Match one of the possible outputs
			return
	print "FAILED: " + exp_file #Does not match any possible outputs

if __name__ == "__main__":
	main()